package au.edu.deakin.ice.meltdown;

import java.util.HashMap;

import android.annotation.SuppressLint;
import android.content.Context;
import android.media.AudioManager;
import android.media.SoundPool;


/** Responsible for managing a SoundPool and exposing the sound playing capabilities to the parent app */
@SuppressLint("UseSparseArrays")
public class SoundManager {
	
/*
 * use
 * SOUNDPOOOL
 * example http://blog.nelsondev.net/?p=207
 * 
 * 
 */
	/** SoundPool */
	private SoundPool mSounds;
	/** A map of valid sound IDs, generated by SoundManager to resource ID's that can be used to play sounds */
	private HashMap<Integer, Integer> soundsMap;
	/** Number of sounds loaded */
	private int soundCount;
	/** App context used to laod sounds */
	private static Context context;
	
	/** Pass app context so that soundmaanger can load sounds from it
	 * @param c The context to store */
	public static void setContext(Context c){
		context = c;
	}
	
	/** Constructor */
	@SuppressLint("UseSparseArrays") //we need hash maps so that we can search and shut down any dangling sounds in OnDestroy
	public SoundManager() {
		mSounds = new SoundPool(8, AudioManager.USE_DEFAULT_STREAM_TYPE, 100);
		soundsMap = new HashMap<Integer, Integer>();
		soundCount = 0;
	}
	
	/** Load a sounds into memory
	 * @param soundResource The resource id to load eg. R.res.soundfile
	 * @return the sound id that can be used to play the sound */
	public int load(int soundResource){
		if(mSounds == null) {
			return -1;
		}
		
		soundsMap.put(++soundCount, mSounds.load(context, soundResource, 1));
		
		return soundCount;
	}
	
	/** Play a sound 
	 * @param soundid the sound to play
	 * @param loop True to loop the sound false to play only once*/
	public void play(int soundid, boolean loop){
		int looping = 0;
		
		if(loop)
			looping = -1;
		
		if(soundid < 0 || soundid > soundCount)
			return; //sound wasn't loaded correctly or a junk id is being passed.
			
		//loop until it starts playing successfully
		//this can be needed if the sound starts playing too soon after being loaded
		//we're really waiting for the filesystem to properly cache the sound file
		while(mSounds.play(soundsMap.get(soundid), 1, 1, 1, looping, 1) == 0);
	}
	
	/** Pause a sound 
	 * @param sound the sound to pause*/
	public void pause(int sound){
		mSounds.pause(sound);
	}
	/** Resume a sound 
	 * @param sound the sound to resume*/
	public void resume(int sound){
		mSounds.resume(sound);
	}
	/** stop playing a sound 
	 * @param sound the sound to stop*/
	public void stop(int sound){
		mSounds.stop(sound);
	}
	/** Cleanup and stop any sounds */
	public void OnDestroy(){
		for (int value :  soundsMap.values()) {
		    mSounds.stop(value);
		    mSounds.unload(value);
		}
	}
}
